### ISSUE TITLE
Syntax error in action.yml for specifying image

### ISSUE THREAD

**Issue by Sh1nku** [dbanty/rust-github-action-template#8]
Hi, thanks a lot for the template. I ran into an error when trying to use my action with
```yaml
- uses: <user>/<repo>:<tag>
# Instead of
- uses: ./
```
```
Error: 'ghcr.io/sh1nku/count-loc-action:v1' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```
https://github.com/dbanty/rust-github-action-template/blob/069fdc1b20e6f22e837c7d5273d889d1c0b6c577/action.yml#L14
This should be prefixed with `docker://` to work externally
